---

- name: Disable some unneeded services
  service: name={{ item }} enabled=no state=stopped
  ignore_errors: yes
  with_items:
    - puppet
    - chef-client

- name: Install binary requirements
  apt: package={{item}} state=present
  with_items:
    - git
    - htop
    - ncbi-blast+
    - openjdk-7-jre
    - samtools
    - scons
